[package]
name = "hosfist"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
main = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
